name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call CapRover Webhook
        run: curl -X POST "${{ secrets.CAPROVER_WEBHOOK_URL }}"
