name: Sync main to staging

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync main -> staging
        env:
          GH_PAT: ${{ secrets.GH_PAT_SYNC }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git fetch origin staging
          git checkout staging
          git merge origin/main --no-edit
          git push origin staging
