name: Sync main to staging

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync main -> staging
        run: |
          git remote add authed-origin https://x-access-token:${{ secrets.GH_PAT_SYNC }}@github.com/${{ github.repository }}
          git fetch authed-origin staging
          git fetch authed-origin main

          # Erstelle lokalen staging-Branch explizit aus authed-origin
          git checkout -b staging authed-origin/staging

          # Merge main rein (aus authed-origin)
          git merge authed-origin/main --no-edit

          # Push zurück zu authed-origin
          git push authed-origin staging
      
